mali_kbase: mem_linux: convert to shrinker_register() (v6.7 compatibility)
Linux commit [1] has removed some old shrinker APIs and this causes
this OOT pixel driver to fail compilation:

    .../gpu/mali_kbase/mali_kbase_mem_linux.c:785:2: error: call to undeclared function 'register_shrinker'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            register_shrinker(&kctx->reclaim, "mali-mem");
            ^
    .../gpu/mali_kbase/mali_kbase_mem_linux.c:785:2: note: did you mean 'register_chrdev'?
    .../common/include/linux/fs.h:2604:19: note: 'register_chrdev' declared here
    static inline int register_chrdev(unsigned int major, const char *name,
                      ^
    .../gpu/mali_kbase/mali_kbase_mem_linux.c:792:2: error: call to undeclared function 'unregister_shrinker'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            unregister_shrinker(&kctx->reclaim);
            ^
    .../gpu/mali_kbase/mali_kbase_mem_linux.c:792:2: note: did you mean 'unregister_chrdev'?
    .../common/include/linux/fs.h:2610:20: note: 'unregister_chrdev' declared here
    static inline void unregister_chrdev(unsigned int major, const char *name)
                       ^
    2 errors generated.

Update the driver accordingly.

Note that it's needlessly hard to keep the #ifdef'ery for older
kernels, so we just drop them at this stage.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f2383e01507e
    ("mm: shrinker: remove old APIs")

Bug: 316904748
Test: TH
Change-Id: Ib9745e462e871ff82f309463b052c3065b13c2d4
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit 0cbb8a3bd94e971514630802d5d2cf156dbbd09e)